// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: TrabajoCompiladores/src/archivos/lexico/lexico.flex

/* JFlex example: partial Java language lexer specification */
package archivos.lexico;
/**
 * This class is a simple example lexer.
 */

// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
public class MiLexico implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int STRING = 2;
  public static final int Comment = 4;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1,  1,  2, 2
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\1\u0100\1\u0200\1\u0300\1\u0400\1\u0500\1\u0600\1\u0700"+
    "\1\u0800\1\u0900\1\u0a00\1\u0b00\1\u0c00\1\u0d00\1\u0e00\1\u0f00"+
    "\1\u1000\1\u0100\1\u1100\1\u1200\1\u1300\1\u0100\1\u1400\1\u1500"+
    "\1\u1600\1\u1700\1\u1800\1\u1900\1\u1a00\1\u1b00\1\u0100\1\u1c00"+
    "\1\u1d00\1\u1e00\2\u1f00\1\u2000\7\u1f00\1\u2100\1\u2200\1\u2300"+
    "\1\u1f00\1\u2400\1\u2500\2\u1f00\31\u0100\1\u2600\121\u0100\1\u2700"+
    "\4\u0100\1\u2800\1\u0100\1\u2900\1\u2a00\1\u2b00\1\u2c00\1\u2d00"+
    "\1\u2e00\53\u0100\1\u2f00\10\u3000\31\u1f00\1\u0100\1\u3100\1\u3200"+
    "\1\u0100\1\u3300\1\u3400\1\u3500\1\u3600\1\u3700\1\u3800\1\u3900"+
    "\1\u3a00\1\u3b00\1\u0100\1\u3c00\1\u3d00\1\u3e00\1\u3f00\1\u4000"+
    "\1\u4100\1\u4200\1\u1f00\1\u4300\1\u4400\1\u4500\1\u4600\1\u4700"+
    "\1\u4800\1\u4900\1\u4a00\1\u4b00\1\u4c00\1\u4d00\1\u4e00\1\u1f00"+
    "\1\u4f00\1\u5000\1\u5100\1\u1f00\3\u0100\1\u5200\1\u5300\1\u5400"+
    "\12\u1f00\4\u0100\1\u5500\17\u1f00\2\u0100\1\u5600\41\u1f00\2\u0100"+
    "\1\u5700\1\u5800\2\u1f00\1\u5900\1\u5a00\27\u0100\1\u5b00\2\u0100"+
    "\1\u5c00\45\u1f00\1\u0100\1\u5d00\1\u5e00\11\u1f00\1\u5f00\24\u1f00"+
    "\1\u6000\1\u6100\1\u1f00\1\u6200\1\u6300\1\u6400\1\u6500\2\u1f00"+
    "\1\u6600\5\u1f00\1\u6700\1\u6800\1\u6900\5\u1f00\1\u6a00\1\u6b00"+
    "\4\u1f00\1\u6c00\2\u1f00\1\u6d00\16\u1f00\246\u0100\1\u6e00\20\u0100"+
    "\1\u6f00\1\u7000\25\u0100\1\u7100\34\u0100\1\u7200\14\u1f00\2\u0100"+
    "\1\u7300\u0b06\u1f00\1\u2700\u02fe\u1f00";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\2\3\1\4\22\0\1\1\1\5"+
    "\1\6\1\7\4\0\1\10\1\11\1\12\1\13\1\14"+
    "\1\15\1\16\1\17\12\20\1\21\1\22\1\23\1\24"+
    "\1\25\2\0\2\26\1\27\27\26\1\30\1\31\1\32"+
    "\1\0\1\33\1\0\1\34\1\35\1\36\1\37\1\40"+
    "\1\41\1\42\1\43\1\44\2\26\1\45\1\46\1\47"+
    "\1\50\1\51\1\26\1\52\1\53\1\54\1\55\1\26"+
    "\1\56\1\26\1\57\1\26\12\0\1\3\32\0\1\1"+
    "\11\0\1\26\12\0\1\26\4\0\1\26\5\0\27\26"+
    "\1\0\37\26\1\0\u01ca\26\4\0\14\26\16\0\5\26"+
    "\7\0\1\26\1\0\1\26\21\0\165\26\1\0\2\26"+
    "\2\0\4\26\1\0\1\26\6\0\1\26\1\0\3\26"+
    "\1\0\1\26\1\0\24\26\1\0\123\26\1\0\213\26"+
    "\1\0\255\26\1\0\46\26\2\0\1\26\6\0\51\26"+
    "\10\0\55\26\1\0\1\26\1\0\2\26\1\0\2\26"+
    "\1\0\1\26\10\0\33\26\4\0\4\26\35\0\13\26"+
    "\5\0\100\26\12\20\4\0\146\26\1\0\10\26\2\0"+
    "\12\26\1\0\6\26\12\20\3\26\2\0\1\26\20\0"+
    "\73\26\2\0\145\26\16\0\12\20\54\26\4\0\1\26"+
    "\2\0\1\26\2\0\56\26\22\0\34\26\4\0\13\26"+
    "\65\0\25\26\1\0\10\26\25\0\17\26\1\0\201\26"+
    "\2\0\12\20\1\0\23\26\1\0\10\26\2\0\2\26"+
    "\2\0\26\26\1\0\7\26\1\0\1\26\3\0\4\26"+
    "\2\0\11\26\2\0\2\26\2\0\4\26\10\0\1\26"+
    "\4\0\2\26\1\0\5\26\2\0\12\20\2\26\12\0"+
    "\1\26\1\0\1\26\2\0\3\26\1\0\6\26\4\0"+
    "\2\26\2\0\26\26\1\0\7\26\1\0\2\26\1\0"+
    "\2\26\1\0\2\26\2\0\1\26\1\0\5\26\4\0"+
    "\2\26\2\0\3\26\3\0\1\26\7\0\4\26\1\0"+
    "\1\26\7\0\12\20\6\26\13\0\3\26\1\0\11\26"+
    "\1\0\3\26\1\0\26\26\1\0\7\26\1\0\2\26"+
    "\1\0\5\26\2\0\12\26\1\0\3\26\1\0\3\26"+
    "\2\0\1\26\17\0\4\26\2\0\12\20\11\0\7\26"+
    "\1\0\3\26\1\0\10\26\2\0\2\26\2\0\26\26"+
    "\1\0\7\26\1\0\2\26\1\0\5\26\2\0\11\26"+
    "\2\0\2\26\2\0\3\26\10\0\2\26\4\0\2\26"+
    "\1\0\5\26\2\0\12\20\1\0\1\26\20\0\2\26"+
    "\1\0\6\26\3\0\3\26\1\0\4\26\3\0\2\26"+
    "\1\0\1\26\1\0\2\26\3\0\2\26\3\0\3\26"+
    "\3\0\14\26\4\0\5\26\3\0\3\26\1\0\4\26"+
    "\2\0\1\26\6\0\1\26\16\0\12\20\20\0\15\26"+
    "\1\0\3\26\1\0\27\26\1\0\20\26\3\0\10\26"+
    "\1\0\3\26\1\0\4\26\7\0\2\26\1\0\3\26"+
    "\5\0\4\26\2\0\12\20\20\0\4\26\1\0\10\26"+
    "\1\0\3\26\1\0\27\26\1\0\12\26\1\0\5\26"+
    "\2\0\11\26\1\0\3\26\1\0\4\26\7\0\2\26"+
    "\7\0\1\26\1\0\4\26\2\0\12\20\1\0\2\26"+
    "\15\0\4\26\1\0\10\26\1\0\3\26\1\0\63\26"+
    "\1\0\3\26\1\0\5\26\5\0\4\26\7\0\5\26"+
    "\2\0\12\20\12\0\6\26\2\0\2\26\1\0\22\26"+
    "\3\0\30\26\1\0\11\26\1\0\1\26\2\0\7\26"+
    "\3\0\1\26\4\0\6\26\1\0\1\26\1\0\10\26"+
    "\6\0\12\20\2\0\2\26\15\0\72\26\5\0\17\26"+
    "\1\0\12\20\47\0\2\26\1\0\1\26\1\0\5\26"+
    "\1\0\30\26\1\0\1\26\1\0\27\26\2\0\5\26"+
    "\1\0\1\26\1\0\6\26\2\0\12\20\2\0\4\26"+
    "\40\0\1\26\27\0\2\26\6\0\12\20\13\0\1\26"+
    "\1\0\1\26\1\0\1\26\4\0\12\26\1\0\44\26"+
    "\4\0\24\26\1\0\22\26\1\0\44\26\11\0\1\26"+
    "\71\0\100\26\12\20\6\0\100\26\12\20\4\26\2\0"+
    "\46\26\1\0\1\26\5\0\1\26\2\0\53\26\1\0"+
    "\115\26\1\0\4\26\2\0\7\26\1\0\1\26\1\0"+
    "\4\26\2\0\51\26\1\0\4\26\2\0\41\26\1\0"+
    "\4\26\2\0\7\26\1\0\1\26\1\0\4\26\2\0"+
    "\17\26\1\0\71\26\1\0\4\26\2\0\103\26\2\0"+
    "\3\26\40\0\20\26\20\0\126\26\2\0\6\26\3\0"+
    "\u016c\26\2\0\21\26\1\1\32\26\5\0\113\26\3\0"+
    "\13\26\7\0\15\26\1\0\7\26\13\0\25\26\13\0"+
    "\24\26\14\0\15\26\1\0\3\26\1\0\2\26\14\0"+
    "\124\26\3\0\1\26\4\0\2\26\2\0\12\20\41\0"+
    "\3\26\2\0\12\20\6\0\131\26\7\0\53\26\5\0"+
    "\106\26\12\0\37\26\1\0\14\26\4\0\14\26\12\0"+
    "\12\20\36\26\2\0\5\26\13\0\54\26\4\0\32\26"+
    "\6\0\12\20\46\0\34\26\4\0\77\26\1\0\35\26"+
    "\2\0\1\26\12\20\6\0\12\20\15\0\1\26\10\0"+
    "\17\26\101\0\114\26\4\0\12\20\21\0\11\26\14\0"+
    "\60\26\12\20\72\26\14\0\70\26\10\0\12\20\3\0"+
    "\3\26\12\20\44\26\2\0\11\26\7\0\53\26\2\0"+
    "\3\26\20\0\3\26\1\0\47\26\5\0\372\26\1\0"+
    "\33\26\2\0\6\26\2\0\46\26\2\0\6\26\2\0"+
    "\10\26\1\0\1\26\1\0\1\26\1\0\1\26\1\0"+
    "\37\26\2\0\65\26\1\0\7\26\1\0\1\26\3\0"+
    "\3\26\1\0\7\26\3\0\4\26\2\0\6\26\4\0"+
    "\15\26\5\0\3\26\1\0\7\26\3\0\13\1\21\0"+
    "\2\60\12\0\2\3\5\0\1\1\17\0\2\26\23\0"+
    "\1\26\12\0\1\1\21\0\1\26\15\0\1\26\20\0"+
    "\15\26\63\0\41\26\21\0\1\26\4\0\1\26\2\0"+
    "\12\26\1\0\1\26\3\0\5\26\6\0\1\26\1\0"+
    "\1\26\1\0\1\26\1\0\4\26\1\0\13\26\2\0"+
    "\4\26\5\0\5\26\4\0\1\26\21\0\51\26\u022d\0"+
    "\64\26\26\0\57\26\1\0\57\26\1\0\205\26\6\0"+
    "\11\26\14\0\46\26\1\0\1\26\5\0\1\26\2\0"+
    "\70\26\7\0\1\26\17\0\30\26\11\0\7\26\1\0"+
    "\7\26\1\0\7\26\1\0\7\26\1\0\7\26\1\0"+
    "\7\26\1\0\7\26\1\0\7\26\1\0\40\26\57\0"+
    "\1\26\320\0\1\1\4\0\3\26\31\0\17\26\1\0"+
    "\5\26\2\0\5\26\4\0\126\26\2\0\2\26\2\0"+
    "\3\26\1\0\132\26\1\0\4\26\5\0\53\26\1\0"+
    "\136\26\21\0\33\26\65\0\306\26\112\0\360\26\20\0"+
    "\215\26\103\0\56\26\2\0\15\26\3\0\20\26\12\20"+
    "\2\26\24\0\63\26\1\0\12\26\1\0\163\26\45\0"+
    "\11\26\2\0\147\26\2\0\65\26\2\0\5\26\60\0"+
    "\61\26\30\0\64\26\14\0\106\26\12\0\12\20\6\0"+
    "\30\26\3\0\1\26\1\0\3\26\12\20\44\26\2\0"+
    "\44\26\14\0\35\26\3\0\101\26\16\0\1\26\12\20"+
    "\6\0\20\26\12\20\5\26\1\0\67\26\11\0\16\26"+
    "\2\0\12\20\6\0\27\26\3\0\111\26\30\0\3\26"+
    "\2\0\20\26\2\0\5\26\12\0\6\26\2\0\6\26"+
    "\2\0\6\26\11\0\7\26\1\0\7\26\1\0\53\26"+
    "\1\0\14\26\10\0\173\26\1\0\2\26\2\0\12\20"+
    "\6\0\244\26\14\0\27\26\4\0\61\26\4\0\u0100\61"+
    "\156\26\2\0\152\26\46\0\7\26\14\0\5\26\5\0"+
    "\14\26\1\0\15\26\1\0\5\26\1\0\1\26\1\0"+
    "\2\26\1\0\2\26\1\0\154\26\41\0\153\26\22\0"+
    "\100\26\2\0\66\26\50\0\14\26\4\0\20\26\20\0"+
    "\20\26\3\0\2\26\30\0\3\26\40\0\5\26\1\0"+
    "\207\26\23\0\12\20\7\0\32\26\4\0\1\26\1\0"+
    "\32\26\13\0\131\26\3\0\6\26\2\0\6\26\2\0"+
    "\6\26\2\0\3\26\43\0\14\26\1\0\32\26\1\0"+
    "\23\26\1\0\2\26\1\0\17\26\2\0\16\26\42\0"+
    "\173\26\105\0\65\26\210\0\1\26\202\0\35\26\3\0"+
    "\61\26\17\0\1\26\37\0\40\26\15\0\36\26\5\0"+
    "\53\26\5\0\36\26\2\0\44\26\4\0\10\26\1\0"+
    "\5\26\52\0\236\26\2\0\12\20\6\0\44\26\4\0"+
    "\44\26\4\0\50\26\10\0\64\26\234\0\67\26\11\0"+
    "\26\26\12\0\10\26\230\0\6\26\2\0\1\26\1\0"+
    "\54\26\1\0\2\26\3\0\1\26\2\0\27\26\12\0"+
    "\27\26\11\0\37\26\101\0\23\26\1\0\2\26\12\0"+
    "\26\26\12\0\32\26\106\0\70\26\6\0\2\26\100\0"+
    "\4\26\1\0\2\26\5\0\10\26\1\0\3\26\1\0"+
    "\35\26\2\0\3\26\4\0\1\26\40\0\35\26\3\0"+
    "\35\26\43\0\10\26\1\0\36\26\31\0\66\26\12\0"+
    "\26\26\12\0\23\26\15\0\22\26\156\0\111\26\67\0"+
    "\63\26\15\0\63\26\15\0\50\26\10\0\12\20\306\0"+
    "\35\26\12\0\1\26\10\0\41\26\217\0\27\26\11\0"+
    "\107\26\37\0\12\20\17\0\74\26\25\0\31\26\7\0"+
    "\12\20\6\0\65\26\1\0\12\20\4\0\3\26\11\0"+
    "\44\26\2\0\1\26\11\0\105\26\4\0\4\26\3\0"+
    "\12\20\1\26\1\0\1\26\43\0\22\26\1\0\45\26"+
    "\6\0\1\26\101\0\7\26\1\0\1\26\1\0\4\26"+
    "\1\0\17\26\1\0\12\26\7\0\73\26\5\0\12\20"+
    "\6\0\4\26\1\0\10\26\2\0\2\26\2\0\26\26"+
    "\1\0\7\26\1\0\2\26\1\0\5\26\1\0\12\26"+
    "\2\0\2\26\2\0\3\26\2\0\1\26\6\0\1\26"+
    "\5\0\7\26\2\0\7\26\3\0\5\26\213\0\113\26"+
    "\5\0\12\20\4\0\2\26\40\0\106\26\1\0\1\26"+
    "\10\0\12\20\246\0\66\26\2\0\11\26\27\0\6\26"+
    "\42\0\101\26\3\0\1\26\13\0\12\20\46\0\71\26"+
    "\7\0\12\20\66\0\33\26\2\0\17\26\4\0\12\20"+
    "\306\0\73\26\145\0\100\26\12\20\25\0\1\26\240\0"+
    "\10\26\2\0\56\26\2\0\10\26\1\0\2\26\33\0"+
    "\77\26\10\0\1\26\10\0\112\26\3\0\1\26\42\0"+
    "\71\26\7\0\11\26\1\0\55\26\1\0\11\26\17\0"+
    "\12\20\30\0\36\26\2\0\26\26\1\0\16\26\111\0"+
    "\7\26\1\0\2\26\1\0\54\26\3\0\1\26\1\0"+
    "\2\26\1\0\11\26\10\0\12\20\6\0\6\26\1\0"+
    "\2\26\1\0\45\26\1\0\2\26\1\0\6\26\7\0"+
    "\12\20\u0136\0\27\26\11\0\232\26\146\0\157\26\21\0"+
    "\304\26\274\0\57\26\321\0\107\26\271\0\71\26\7\0"+
    "\37\26\1\0\12\20\146\0\36\26\2\0\5\26\13\0"+
    "\67\26\11\0\4\26\14\0\12\20\11\0\25\26\5\0"+
    "\23\26\260\0\100\26\200\0\113\26\4\0\71\26\7\0"+
    "\21\26\100\0\2\26\1\0\1\26\34\0\370\26\10\0"+
    "\363\26\15\0\37\26\61\0\3\26\21\0\4\26\10\0"+
    "\u018c\26\4\0\153\26\5\0\15\26\3\0\11\26\7\0"+
    "\12\26\3\0\2\26\306\0\5\26\3\0\6\26\10\0"+
    "\10\26\2\0\7\26\36\0\4\26\224\0\3\26\273\0"+
    "\125\26\1\0\107\26\1\0\2\26\2\0\1\26\2\0"+
    "\2\26\2\0\4\26\1\0\14\26\1\0\1\26\1\0"+
    "\7\26\1\0\101\26\1\0\4\26\2\0\10\26\1\0"+
    "\7\26\1\0\34\26\1\0\4\26\1\0\5\26\1\0"+
    "\1\26\3\0\7\26\1\0\u0154\26\2\0\31\26\1\0"+
    "\31\26\1\0\37\26\1\0\31\26\1\0\37\26\1\0"+
    "\31\26\1\0\37\26\1\0\31\26\1\0\37\26\1\0"+
    "\31\26\1\0\10\26\2\0\62\20\67\26\4\0\62\26"+
    "\10\0\1\26\16\0\1\26\26\0\5\26\1\0\17\26"+
    "\120\0\7\26\1\0\21\26\2\0\7\26\1\0\2\26"+
    "\1\0\5\26\325\0\55\26\3\0\16\26\2\0\12\20"+
    "\4\0\1\26\u0171\0\60\26\12\20\6\0\305\26\13\0"+
    "\7\26\51\0\114\26\4\0\12\20\246\0\4\26\1\0"+
    "\33\26\1\0\2\26\1\0\1\26\2\0\1\26\1\0"+
    "\12\26\1\0\4\26\1\0\1\26\1\0\1\26\6\0"+
    "\1\26\4\0\1\26\1\0\1\26\1\0\1\26\1\0"+
    "\3\26\1\0\2\26\1\0\1\26\2\0\1\26\1\0"+
    "\1\26\1\0\1\26\1\0\1\26\1\0\1\26\1\0"+
    "\2\26\1\0\1\26\2\0\4\26\1\0\7\26\1\0"+
    "\4\26\1\0\4\26\1\0\1\26\1\0\12\26\1\0"+
    "\21\26\5\0\3\26\1\0\5\26\1\0\21\26\164\0"+
    "\32\26\6\0\32\26\6\0\32\26\166\0\327\26\51\0"+
    "\65\26\13\0\336\26\2\0\u0182\26\16\0\u0131\26\37\0"+
    "\36\26\342\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[29696];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\3\0\1\1\2\2\1\1\1\3\1\4\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\1\1\13\1\14\1\15"+
    "\1\16\1\17\1\1\1\20\2\21\1\22\1\23\13\21"+
    "\1\24\1\25\1\26\1\27\3\30\1\31\2\4\1\32"+
    "\1\33\1\34\1\35\1\36\1\37\1\40\5\21\1\41"+
    "\4\21\1\42\2\21\1\43\4\21\1\44\1\45\1\46"+
    "\1\47\1\50\1\51\1\21\1\52\4\21\1\53\3\21"+
    "\1\54\1\55\4\21\1\56\1\57\2\21\1\60\5\21"+
    "\1\61\1\62\5\21\1\63\2\21\1\64\7\21\1\65"+
    "\6\21\1\0\5\21\2\0\4\21\1\66\2\0\2\21"+
    "\1\67\1\21\4\0\1\70\15\0\1\71\2\0\1\72"+
    "\4\0\1\73\1\74";

  private static int [] zzUnpackAction() {
    int [] result = new int[177];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\62\0\144\0\226\0\226\0\310\0\372\0\226"+
    "\0\u012c\0\u015e\0\226\0\u0190\0\226\0\226\0\226\0\u01c2"+
    "\0\226\0\u01f4\0\u0226\0\226\0\u0258\0\u028a\0\u02bc\0\u02ee"+
    "\0\u0320\0\226\0\226\0\u0352\0\u0384\0\u03b6\0\u03e8\0\u041a"+
    "\0\u044c\0\u047e\0\u04b0\0\u04e2\0\u0514\0\u0546\0\226\0\u0578"+
    "\0\226\0\u05aa\0\226\0\u05dc\0\u060e\0\226\0\226\0\u0640"+
    "\0\226\0\226\0\u01c2\0\226\0\226\0\226\0\226\0\u0672"+
    "\0\u06a4\0\u06d6\0\u0708\0\u073a\0\u02ee\0\u076c\0\u079e\0\u07d0"+
    "\0\u0802\0\u02ee\0\u0834\0\u0866\0\u02ee\0\u0898\0\u08ca\0\u08fc"+
    "\0\u092e\0\226\0\226\0\226\0\226\0\226\0\226\0\u0960"+
    "\0\u02ee\0\u0992\0\u09c4\0\u09f6\0\u0a28\0\u0a5a\0\u0a8c\0\u0abe"+
    "\0\u0af0\0\u02ee\0\u02ee\0\u0b22\0\u0b54\0\u0b86\0\u0bb8\0\u02ee"+
    "\0\u02ee\0\u0bea\0\u0c1c\0\u02ee\0\u0c4e\0\u0c80\0\u0cb2\0\u0ce4"+
    "\0\u0d16\0\u02ee\0\u02ee\0\u0d48\0\u0d7a\0\u0dac\0\u0dde\0\u0e10"+
    "\0\u02ee\0\u0e42\0\u0e74\0\u02ee\0\u0ea6\0\u0ed8\0\u0f0a\0\u0f3c"+
    "\0\u0f6e\0\u0fa0\0\u0fd2\0\u02ee\0\u1004\0\u1036\0\u1068\0\u109a"+
    "\0\u10cc\0\u10fe\0\u1130\0\u1162\0\u1194\0\u11c6\0\u11f8\0\u122a"+
    "\0\u125c\0\u128e\0\u12c0\0\u12f2\0\u1324\0\u1356\0\u02ee\0\u1388"+
    "\0\u13ba\0\u13ec\0\u141e\0\u02ee\0\u1450\0\u1482\0\u14b4\0\u14e6"+
    "\0\u1518\0\u02ee\0\u154a\0\u157c\0\u15ae\0\u15e0\0\u1612\0\u1644"+
    "\0\u1676\0\u16a8\0\u16da\0\u170c\0\u173e\0\u1770\0\u17a2\0\226"+
    "\0\u17d4\0\u1806\0\226\0\u1838\0\u186a\0\u189c\0\u18ce\0\226"+
    "\0\226";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[177];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\4\3\5\1\6\1\7\1\10\1\11\1\12\1\13"+
    "\1\14\1\15\1\16\1\17\1\20\1\21\1\22\1\23"+
    "\1\24\1\25\1\26\1\27\1\30\1\31\1\32\1\4"+
    "\1\33\1\4\1\34\1\35\1\31\1\36\1\37\1\40"+
    "\2\30\1\41\2\30\1\42\1\43\1\44\2\30\1\45"+
    "\1\30\1\46\1\30\1\47\1\4\2\50\1\4\1\50"+
    "\1\4\1\50\1\51\22\50\1\52\30\50\10\53\1\54"+
    "\1\53\1\55\47\53\64\0\1\5\103\0\1\56\35\0"+
    "\2\11\1\57\1\0\1\60\54\11\13\0\1\61\60\0"+
    "\1\62\70\0\1\63\57\0\1\63\1\0\1\22\65\0"+
    "\1\64\61\0\1\65\61\0\1\66\61\0\1\67\55\0"+
    "\1\30\5\0\2\30\3\0\25\30\22\0\1\30\5\0"+
    "\2\30\3\0\15\30\1\70\7\30\22\0\1\30\5\0"+
    "\2\30\3\0\14\30\1\71\10\30\22\0\1\30\5\0"+
    "\2\30\3\0\15\30\1\72\7\30\22\0\1\30\5\0"+
    "\2\30\3\0\5\30\1\73\3\30\1\74\3\30\1\75"+
    "\7\30\22\0\1\30\5\0\2\30\3\0\12\30\1\76"+
    "\1\30\1\77\10\30\22\0\1\30\5\0\2\30\3\0"+
    "\1\30\1\100\10\30\1\101\12\30\22\0\1\30\5\0"+
    "\2\30\3\0\6\30\1\102\5\30\1\103\10\30\22\0"+
    "\1\30\5\0\2\30\3\0\15\30\1\104\7\30\22\0"+
    "\1\30\5\0\2\30\3\0\17\30\1\105\5\30\22\0"+
    "\1\30\5\0\2\30\3\0\17\30\1\106\5\30\22\0"+
    "\1\30\5\0\2\30\3\0\10\30\1\107\6\30\1\110"+
    "\5\30\22\0\1\30\5\0\2\30\3\0\10\30\1\111"+
    "\14\30\2\0\2\50\1\0\1\50\1\0\1\50\1\0"+
    "\22\50\1\0\30\50\6\0\1\112\40\0\1\113\2\0"+
    "\1\114\1\0\1\115\17\0\1\116\60\0\1\117\52\0"+
    "\1\57\77\0\1\30\5\0\2\30\3\0\12\30\1\120"+
    "\12\30\22\0\1\30\5\0\2\30\3\0\4\30\1\121"+
    "\20\30\22\0\1\30\5\0\2\30\3\0\15\30\1\122"+
    "\7\30\22\0\1\30\5\0\2\30\3\0\3\30\1\123"+
    "\21\30\22\0\1\30\5\0\2\30\3\0\20\30\1\124"+
    "\4\30\22\0\1\30\5\0\2\30\3\0\20\30\1\125"+
    "\4\30\22\0\1\30\5\0\2\30\3\0\4\30\1\126"+
    "\20\30\22\0\1\30\5\0\2\30\3\0\12\30\1\127"+
    "\12\30\22\0\1\30\5\0\2\30\3\0\15\30\1\130"+
    "\7\30\22\0\1\30\5\0\2\30\3\0\16\30\1\131"+
    "\2\30\1\132\3\30\22\0\1\30\5\0\2\30\3\0"+
    "\21\30\1\133\3\30\22\0\1\30\5\0\2\30\3\0"+
    "\15\30\1\134\7\30\22\0\1\30\5\0\2\30\3\0"+
    "\5\30\1\135\17\30\22\0\1\30\5\0\2\30\3\0"+
    "\22\30\1\136\2\30\22\0\1\30\5\0\2\30\3\0"+
    "\11\30\1\137\13\30\22\0\1\30\5\0\2\30\3\0"+
    "\1\30\1\140\23\30\22\0\1\30\5\0\2\30\3\0"+
    "\12\30\1\141\12\30\22\0\1\30\5\0\2\30\3\0"+
    "\12\30\1\142\12\30\22\0\1\30\5\0\2\30\3\0"+
    "\16\30\1\143\6\30\22\0\1\30\5\0\2\30\3\0"+
    "\5\30\1\144\17\30\22\0\1\30\5\0\2\30\3\0"+
    "\4\30\1\145\11\30\1\146\6\30\22\0\1\30\5\0"+
    "\2\30\3\0\20\30\1\136\4\30\22\0\1\30\5\0"+
    "\2\30\3\0\1\30\1\147\23\30\22\0\1\30\5\0"+
    "\2\30\3\0\22\30\1\150\2\30\22\0\1\30\5\0"+
    "\2\30\3\0\7\30\1\151\15\30\22\0\1\30\5\0"+
    "\2\30\3\0\14\30\1\152\10\30\22\0\1\30\5\0"+
    "\2\30\3\0\5\30\1\153\17\30\22\0\1\30\5\0"+
    "\2\30\3\0\12\30\1\154\12\30\22\0\1\30\5\0"+
    "\2\30\3\0\1\30\1\155\23\30\22\0\1\30\5\0"+
    "\2\30\3\0\12\30\1\156\12\30\22\0\1\30\5\0"+
    "\2\30\3\0\5\30\1\157\17\30\22\0\1\30\5\0"+
    "\2\30\3\0\17\30\1\160\5\30\22\0\1\30\5\0"+
    "\2\30\3\0\21\30\1\161\3\30\22\0\1\30\5\0"+
    "\2\30\3\0\21\30\1\162\3\30\22\0\1\30\5\0"+
    "\2\30\3\0\17\30\1\163\5\30\22\0\1\30\5\0"+
    "\2\30\3\0\5\30\1\164\17\30\22\0\1\30\5\0"+
    "\2\30\3\0\17\30\1\165\5\30\22\0\1\30\5\0"+
    "\2\30\3\0\1\30\1\166\23\30\22\0\1\30\5\0"+
    "\2\30\3\0\3\30\1\167\21\30\22\0\1\30\5\0"+
    "\2\30\3\0\15\30\1\170\7\30\22\0\1\30\5\0"+
    "\2\30\3\0\1\171\24\30\22\0\1\30\5\0\2\30"+
    "\3\0\1\30\1\172\23\30\22\0\1\30\5\0\2\30"+
    "\3\0\5\30\1\173\17\30\22\0\1\30\5\0\2\30"+
    "\3\0\24\30\1\174\22\0\1\30\5\0\2\30\3\0"+
    "\12\30\1\175\12\30\22\0\1\30\5\0\2\30\3\0"+
    "\7\30\1\176\15\30\22\0\1\30\5\0\2\30\3\0"+
    "\2\30\1\177\3\30\1\200\2\30\1\201\13\30\22\0"+
    "\1\30\5\0\2\30\3\0\13\30\1\202\11\30\20\0"+
    "\1\203\1\0\1\30\5\0\2\30\3\0\25\30\22\0"+
    "\1\30\5\0\2\30\3\0\1\30\1\204\23\30\22\0"+
    "\1\30\5\0\2\30\3\0\17\30\1\205\5\30\22\0"+
    "\1\30\5\0\2\30\3\0\15\30\1\206\7\30\22\0"+
    "\1\30\5\0\2\30\3\0\12\30\1\207\12\30\22\0"+
    "\1\30\5\0\2\30\3\0\14\30\1\210\10\30\20\0"+
    "\1\211\1\0\1\30\5\0\2\30\3\0\25\30\55\0"+
    "\1\212\26\0\1\30\5\0\2\30\3\0\17\30\1\213"+
    "\5\30\22\0\1\30\5\0\2\30\3\0\1\30\1\214"+
    "\23\30\22\0\1\30\5\0\2\30\3\0\15\30\1\215"+
    "\7\30\22\0\1\30\5\0\2\30\3\0\15\30\1\216"+
    "\7\30\22\0\1\30\5\0\2\30\3\0\21\30\1\217"+
    "\3\30\55\0\1\220\46\0\1\221\41\0\1\30\5\0"+
    "\2\30\3\0\5\30\1\222\17\30\22\0\1\30\5\0"+
    "\2\30\3\0\13\30\1\223\11\30\22\0\1\30\5\0"+
    "\2\30\3\0\12\30\1\224\12\30\22\0\1\30\5\0"+
    "\2\30\3\0\1\30\1\225\23\30\42\0\1\226\57\0"+
    "\1\227\41\0\1\230\1\0\1\30\5\0\2\30\3\0"+
    "\25\30\20\0\1\231\1\0\1\30\5\0\2\30\3\0"+
    "\25\30\22\0\1\30\5\0\2\30\3\0\21\30\1\232"+
    "\3\30\40\0\1\233\77\0\1\234\60\0\1\235\61\0"+
    "\1\236\62\0\1\237\51\0\1\240\55\0\1\241\61\0"+
    "\1\242\65\0\1\243\65\0\1\244\47\0\1\245\61\0"+
    "\1\246\73\0\1\247\60\0\1\250\66\0\1\251\61\0"+
    "\1\252\54\0\1\253\56\0\1\254\61\0\1\255\65\0"+
    "\1\256\61\0\1\257\60\0\1\260\61\0\1\261\12\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[6400];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\3\0\2\11\2\1\1\11\2\1\1\11\1\1\3\11"+
    "\1\1\1\11\2\1\1\11\5\1\2\11\13\1\1\11"+
    "\1\1\1\11\1\1\1\11\2\1\2\11\1\1\2\11"+
    "\1\1\4\11\22\1\6\11\63\1\1\0\5\1\2\0"+
    "\5\1\2\0\4\1\4\0\1\1\15\0\1\11\2\0"+
    "\1\11\4\0\2\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[177];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    /*************************************************************************
    * En esta sección se puede incluir código que se copiará textualmente
    * como parte de la definición de la clase del analizador léxico.
    * Típicamente serán variables de instancia o nuevos métodos de la clase.
    *************************************************************************/

    int string_yyline = 1;
    int string_yycolumn = 1;
    int count_comment = 0;
    int cota_int = 20;
    int cota_ID = 28;
    int cota_float = 25;
    int cantMax_string = 100;


    StringBuffer string = new StringBuffer();

    private MiToken token(String nombre) {
        return new MiToken(nombre, this.yyline, this.yycolumn);
    }

    private MiToken token(String nombre, Object valor) {
        return new MiToken(nombre, this.yyline, this.yycolumn, valor);
    }

    private MiToken token(String nombre, int line, int column, Object valor) {
        return new MiToken(nombre, line, column, valor);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public MiLexico(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public MiToken next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
            switch (zzLexicalState) {
            case Comment: {
              return token("ERROR", "Error comentario no balanceado");
            }  // fall though
            case 178: break;
            default:
              {
                return token("EOF");
              }
        }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { return token("ERROR", "Illegal character <"+yytext()+">");
            }
            // fall through
          case 61: break;
          case 2:
            { /* ignore */
            }
            // fall through
          case 62: break;
          case 3:
            { string.setLength(0);
          yybegin(STRING);
          string_yyline = this.yyline;
          string_yycolumn = this.yycolumn;
            }
            // fall through
          case 63: break;
          case 4:
            { 
            }
            // fall through
          case 64: break;
          case 5:
            { return token("PARENTESISO", yytext());
            }
            // fall through
          case 65: break;
          case 6:
            { return token("PARENTESISC", yytext());
            }
            // fall through
          case 66: break;
          case 7:
            { return token("MULT", yytext());
            }
            // fall through
          case 67: break;
          case 8:
            { return token("SUMA", yytext());
            }
            // fall through
          case 68: break;
          case 9:
            { return token("COMA", yytext());
            }
            // fall through
          case 69: break;
          case 10:
            { return token("RESTA", yytext());
            }
            // fall through
          case 70: break;
          case 11:
            { return token("DIV", yytext());
            }
            // fall through
          case 71: break;
          case 12:
            { int a = yytext().length();
          if ( a < cota_int ) {return token("INT", yytext());}
          else{
              return token("ERROR", "Error supera cantidad maxima de caracteres permitidos");
          }
            }
            // fall through
          case 72: break;
          case 13:
            { return token("DOSPUNTOS", yytext());
            }
            // fall through
          case 73: break;
          case 14:
            { return token("PUNTOCOMA", yytext());
            }
            // fall through
          case 74: break;
          case 15:
            { return token("MENOR",yytext());
            }
            // fall through
          case 75: break;
          case 16:
            { return token("MAYOR",yytext());
            }
            // fall through
          case 76: break;
          case 17:
            { if ( yytext().length() < cota_ID) {return token("IDENTIFIER", yytext());}
          else{
              return token("ERROR", "Error supera cantidad maxima de caracteres permitidos");}
            }
            // fall through
          case 77: break;
          case 18:
            { return token("CORCHETEO", yytext());
            }
            // fall through
          case 78: break;
          case 19:
            { return token("CORCHETEC", yytext());
            }
            // fall through
          case 79: break;
          case 20:
            { return token("COMILLA", yytext());
            }
            // fall through
          case 80: break;
          case 21:
            { string.append( yytext() );
            }
            // fall through
          case 81: break;
          case 22:
            { yybegin(YYINITIAL);
          if (string.length() < cantMax_string) {return token("STRING_LITERAL", string_yyline, string_yycolumn, string.toString());}
          else{
              return token("ERROR", "Error supera cantidad maxima de caracteres permitidos");
          }
            }
            // fall through
          case 82: break;
          case 23:
            { string.append('\\');
            }
            // fall through
          case 83: break;
          case 24:
            { /*nada*/
            }
            // fall through
          case 84: break;
          case 25:
            { return token("DISTINTO",yytext());
            }
            // fall through
          case 85: break;
          case 26:
            { yybegin(Comment);
          count_comment+=1;
            }
            // fall through
          case 86: break;
          case 27:
            { return token("ERROR", "Error comentario no balanceado");
            }
            // fall through
          case 87: break;
          case 28:
            { int a = yytext().length();
          if ( a < cota_float) {return token("FLOAT", yytext());}
          else{
              return token("ERROR", "Error supera cantidad maxima de caracteres permitidos");}
            }
            // fall through
          case 88: break;
          case 29:
            { return token("ASIGN", yytext());
            }
            // fall through
          case 89: break;
          case 30:
            { return token("MENOR_IGUAL",yytext());
            }
            // fall through
          case 90: break;
          case 31:
            { return token("IGUAL",yytext());
            }
            // fall through
          case 91: break;
          case 32:
            { return token("MAYOR_IGUAL",yytext());
            }
            // fall through
          case 92: break;
          case 33:
            { return token("DO", yytext());
            }
            // fall through
          case 93: break;
          case 34:
            { return token("IF", yytext());
            }
            // fall through
          case 94: break;
          case 35:
            { return token("OR", yytext());
            }
            // fall through
          case 95: break;
          case 36:
            { string.append('\"');
            }
            // fall through
          case 96: break;
          case 37:
            { string.append('\n');
            }
            // fall through
          case 97: break;
          case 38:
            { string.append('\r');
            }
            // fall through
          case 98: break;
          case 39:
            { string.append('\t');
            }
            // fall through
          case 99: break;
          case 40:
            { count_comment+=1;
            }
            // fall through
          case 100: break;
          case 41:
            { count_comment-=1;
      if (count_comment==0){
          yybegin(YYINITIAL);
      }
            }
            // fall through
          case 101: break;
          case 42:
            { return token("AND",yytext());
            }
            // fall through
          case 102: break;
          case 43:
            { return token("END", yytext());
            }
            // fall through
          case 103: break;
          case 44:
            { return token("TIPO_INT", yytext());
            }
            // fall through
          case 104: break;
          case 45:
            { return token("NOT", yytext());
            }
            // fall through
          case 105: break;
          case 46:
            { return token("COLA", yytext());
            }
            // fall through
          case 106: break;
          case 47:
            { return token("TIPO_BOOL", yytext());
            }
            // fall through
          case 107: break;
          case 48:
            { return token("ELSE", yytext());
            }
            // fall through
          case 108: break;
          case 49:
            { return token("THEN", yytext());
            }
            // fall through
          case 109: break;
          case 50:
            { return token("BOOL", yytext());
            }
            // fall through
          case 110: break;
          case 51:
            { return token("TIPO_FLOAT", yytext());
            }
            // fall through
          case 111: break;
          case 52:
            { return token("WHILE", yytext());
            }
            // fall through
          case 112: break;
          case 53:
            { return token("DISPLAY", yytext());
            }
            // fall through
          case 113: break;
          case 54:
            { return token("INPUT_INT", yytext());
            }
            // fall through
          case 114: break;
          case 55:
            { return token("INPUT_BOOL", yytext());
            }
            // fall through
          case 115: break;
          case 56:
            { return token("INPUT_FLOAT", yytext());
            }
            // fall through
          case 116: break;
          case 57:
            { return token("DECLARE_SECTION", yytext());
            }
            // fall through
          case 117: break;
          case 58:
            { return token("PROGRAM_SECTION", yytext());
            }
            // fall through
          case 118: break;
          case 59:
            { return token("ENDDECLARE_SECTION", yytext());
            }
            // fall through
          case 119: break;
          case 60:
            { return token("ENDPROGRAM_SECTION", yytext());
            }
            // fall through
          case 120: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
