
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package archivos.jflexyjcup;

/** CUP generated class containing symbol constants. */
public class MiParserSym {
  /* terminals */
  public static final int DISPLAY = 7;
  public static final int DOSPUNTOS = 17;
  public static final int ENDDECLARE_SECTION = 37;
  public static final int STRING_LITERAL = 40;
  public static final int CORCHETEO = 13;
  public static final int MULT = 4;
  public static final int PARENTESISO = 11;
  public static final int RESTA = 3;
  public static final int CORCHETEC = 14;
  public static final int INT = 33;
  public static final int PUNTOCOMA = 15;
  public static final int PARENTESISC = 12;
  public static final int OPCOMP = 27;
  public static final int NOT = 26;
  public static final int AND = 24;
  public static final int OR = 25;
  public static final int BOOL = 35;
  public static final int DIV = 5;
  public static final int SUMA = 2;
  public static final int IF = 20;
  public static final int EOF = 0;
  public static final int INPUT_INT = 8;
  public static final int error = 1;
  public static final int COMA = 16;
  public static final int INPUT_BOOL = 9;
  public static final int TIPO_INT = 28;
  public static final int ELSE = 22;
  public static final int WHILE = 18;
  public static final int FLOAT = 34;
  public static final int THEN = 21;
  public static final int TIPO_FLOAT = 29;
  public static final int PROGRAM_SECTION = 38;
  public static final int TIPO_BOOL = 30;
  public static final int ASIGN = 6;
  public static final int END = 23;
  public static final int INPUT_FLOAT = 10;
  public static final int COLA = 31;
  public static final int ENDPROGRAM_SECTION = 39;
  public static final int DO = 19;
  public static final int DECLARE_SECTION = 36;
  public static final int IDENTIFIER = 32;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SUMA",
  "RESTA",
  "MULT",
  "DIV",
  "ASIGN",
  "DISPLAY",
  "INPUT_INT",
  "INPUT_BOOL",
  "INPUT_FLOAT",
  "PARENTESISO",
  "PARENTESISC",
  "CORCHETEO",
  "CORCHETEC",
  "PUNTOCOMA",
  "COMA",
  "DOSPUNTOS",
  "WHILE",
  "DO",
  "IF",
  "THEN",
  "ELSE",
  "END",
  "AND",
  "OR",
  "NOT",
  "OPCOMP",
  "TIPO_INT",
  "TIPO_FLOAT",
  "TIPO_BOOL",
  "COLA",
  "IDENTIFIER",
  "INT",
  "FLOAT",
  "BOOL",
  "DECLARE_SECTION",
  "ENDDECLARE_SECTION",
  "PROGRAM_SECTION",
  "ENDPROGRAM_SECTION",
  "STRING_LITERAL"
  };
}

