
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package archivos.jflexyjcup;

/** CUP generated class containing symbol constants. */
public class MiParserSym {
  /* terminals */
  public static final int DISPLAY = 7;
  public static final int DOSPUNTOS = 20;
  public static final int ENDDECLARE_SECTION = 41;
  public static final int STRING_LITERAL = 44;
  public static final int CORCHETEO = 14;
  public static final int MULT = 4;
  public static final int PARENTESISO = 11;
  public static final int RESTA = 3;
  public static final int CORCHETEC = 15;
  public static final int INT = 37;
  public static final int PUNTOCOMA = 17;
  public static final int PARENTESISC = 12;
  public static final int OPCOMP = 31;
  public static final int NOT = 30;
  public static final int AND = 28;
  public static final int IGUAL = 27;
  public static final int OR = 29;
  public static final int BOOL = 39;
  public static final int DIV = 5;
  public static final int SUMA = 2;
  public static final int IF = 23;
  public static final int EOF = 0;
  public static final int INPUT_INT = 8;
  public static final int error = 1;
  public static final int COMA = 19;
  public static final int INPUT_BOOL = 9;
  public static final int LLAVEc = 16;
  public static final int TIPO_INT = 32;
  public static final int ELSE = 25;
  public static final int PUNTO = 18;
  public static final int WHILE = 21;
  public static final int FLOAT = 38;
  public static final int THEN = 24;
  public static final int LLAVEO = 13;
  public static final int TIPO_FLOAT = 33;
  public static final int PROGRAM_SECTION = 42;
  public static final int TIPO_BOOL = 34;
  public static final int ASIGN = 6;
  public static final int END = 26;
  public static final int INPUT_FLOAT = 10;
  public static final int COLA = 35;
  public static final int ENDPROGRAM_SECTION = 43;
  public static final int DO = 22;
  public static final int DECLARE_SECTION = 40;
  public static final int IDENTIFIER = 36;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SUMA",
  "RESTA",
  "MULT",
  "DIV",
  "ASIGN",
  "DISPLAY",
  "INPUT_INT",
  "INPUT_BOOL",
  "INPUT_FLOAT",
  "PARENTESISO",
  "PARENTESISC",
  "LLAVEO",
  "CORCHETEO",
  "CORCHETEC",
  "LLAVEc",
  "PUNTOCOMA",
  "PUNTO",
  "COMA",
  "DOSPUNTOS",
  "WHILE",
  "DO",
  "IF",
  "THEN",
  "ELSE",
  "END",
  "IGUAL",
  "AND",
  "OR",
  "NOT",
  "OPCOMP",
  "TIPO_INT",
  "TIPO_FLOAT",
  "TIPO_BOOL",
  "COLA",
  "IDENTIFIER",
  "INT",
  "FLOAT",
  "BOOL",
  "DECLARE_SECTION",
  "ENDDECLARE_SECTION",
  "PROGRAM_SECTION",
  "ENDPROGRAM_SECTION",
  "STRING_LITERAL"
  };
}

