
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package archivos.sintactico;

/** CUP generated class containing symbol constants. */
public class MiParserSym {
  /* terminals */
  public static final int DISPLAY = 14;
  public static final int DOSPUNTOS = 13;
  public static final int ENDDECLARE_SECTION = 44;
  public static final int DISTINTO = 30;
  public static final int STRING_LITERAL = 37;
  public static final int CORCHETEO = 9;
  public static final int MULT = 4;
  public static final int PARENTESISO = 7;
  public static final int RESTA = 3;
  public static final int CORCHETEC = 10;
  public static final int INT = 39;
  public static final int PUNTOCOMA = 11;
  public static final int PARENTESISC = 8;
  public static final int NOT = 26;
  public static final int AND = 24;
  public static final int IGUAL = 29;
  public static final int OR = 25;
  public static final int BOOL = 38;
  public static final int DIV = 5;
  public static final int SUMA = 2;
  public static final int IF = 20;
  public static final int EOF = 0;
  public static final int INPUT_INT = 17;
  public static final int error = 1;
  public static final int COMA = 12;
  public static final int INPUT_BOOL = 19;
  public static final int MENOR = 28;
  public static final int TIPO_INT = 34;
  public static final int ERROR = 40;
  public static final int MAYOR = 27;
  public static final int ELSE = 22;
  public static final int WHILE = 15;
  public static final int MAYOR_IGUAL = 31;
  public static final int FLOAT = 41;
  public static final int THEN = 21;
  public static final int TIPO_FLOAT = 35;
  public static final int PROGRAM_SECTION = 45;
  public static final int TIPO_BOOL = 36;
  public static final int ASIGN = 6;
  public static final int END = 23;
  public static final int INPUT_FLOAT = 18;
  public static final int COLA = 33;
  public static final int ENDPROGRAM_SECTION = 46;
  public static final int MENOR_IGUAL = 32;
  public static final int DO = 16;
  public static final int DECLARE_SECTION = 43;
  public static final int IDENTIFIER = 42;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SUMA",
  "RESTA",
  "MULT",
  "DIV",
  "ASIGN",
  "PARENTESISO",
  "PARENTESISC",
  "CORCHETEO",
  "CORCHETEC",
  "PUNTOCOMA",
  "COMA",
  "DOSPUNTOS",
  "DISPLAY",
  "WHILE",
  "DO",
  "INPUT_INT",
  "INPUT_FLOAT",
  "INPUT_BOOL",
  "IF",
  "THEN",
  "ELSE",
  "END",
  "AND",
  "OR",
  "NOT",
  "MAYOR",
  "MENOR",
  "IGUAL",
  "DISTINTO",
  "MAYOR_IGUAL",
  "MENOR_IGUAL",
  "COLA",
  "TIPO_INT",
  "TIPO_FLOAT",
  "TIPO_BOOL",
  "STRING_LITERAL",
  "BOOL",
  "INT",
  "ERROR",
  "FLOAT",
  "IDENTIFIER",
  "DECLARE_SECTION",
  "ENDDECLARE_SECTION",
  "PROGRAM_SECTION",
  "ENDPROGRAM_SECTION"
  };
}

